### ISSUE TITLE
"Cannot read normals" loading single-part STL in Cura LE 3.6.10

### ISSUE THREAD

**Issue by charles-dyfis-net** [CreativeTools/3DBenchy#1]
Library versions:

- numpy-stl 2.10.1
- Cura, Uranium, &c. 3.6.10 (Lulzbot branch)

```
Exception: Exception occurred while loading file /home/chaduffy/3DBenchy/Single-part/3DBenchy.stl
Traceback (most recent call last):
  File "/nix/store/0acrcmngwskrb1vl4z819xx1p5f3ffjs-python3.7-uraniumLulzbot/lib/python3.7/site-packages/UM/FileHandler/ReadFileJob.py", line 66, in run
    self.setResult(self._handler.readerRead(reader, self._filename))
  File "/nix/store/0acrcmngwskrb1vl4z819xx1p5f3ffjs-python3.7-uraniumLulzbot/lib/python3.7/site-packages/UM/Mesh/MeshFileHandler.py", line 28, in readerRead
    results = reader.read(file_name)
  File "/nix/store/0acrcmngwskrb1vl4z819xx1p5f3ffjs-python3.7-uraniumLulzbot/lib/uranium/plugins/FileHandlers/STLReader/STLReader.py", line 56, in read
    self.load_file(file_name, mesh_builder, _use_numpystl = use_numpystl)
  File "/nix/store/0acrcmngwskrb1vl4z819xx1p5f3ffjs-python3.7-uraniumLulzbot/lib/uranium/plugins/FileHandlers/STLReader/STLReader.py", line 35, in load_file
    self._loadWithNumpySTL(file_name, mesh_builder)
  File "/nix/store/0acrcmngwskrb1vl4z819xx1p5f3ffjs-python3.7-uraniumLulzbot/lib/uranium/plugins/FileHandlers/STLReader/STLReader.py", line 87, in _loadWithNumpySTL
    for loaded_data in stl.mesh.Mesh.from_multi_file(file_name):
  File "/nix/store/vziwy2q7w6h2xl75ykwv81sg83ik7qhx-python3.7-numpy-stl-2.10.1/lib/python3.7/site-packages/stl/stl.py", line 348, in from_multi_file
    raw_data = cls.load(fh, mode=mode, speedups=speedups)
  File "/nix/store/vziwy2q7w6h2xl75ykwv81sg83ik7qhx-python3.7-numpy-stl-2.10.1/lib/python3.7/site-packages/stl/stl.py", line 71, in load
    fh, header, speedups=speedups)
  File "/nix/store/vziwy2q7w6h2xl75ykwv81sg83ik7qhx-python3.7-numpy-stl-2.10.1/lib/python3.7/site-packages/stl/stl.py", line 214, in _load_ascii
    return _speedups.ascii_read(fh, header)
  File "stl/_speedups.pyx", line 142, in stl._speedups.ascii_read
RuntimeError: (0, "Cannot read normals (2:b'\\xd7\\xd3@')")
```

**Comment by charles-dyfis-net** [comment]
Since numpy-stl itself can read the file just fine (for purposes of the stl2txt tool and similar), I'm provisionally calling this something going on with the uranium library's usage pattern rather than a problem with the input file, and closing the ticket pending investigation.

**Comment by charles-dyfis-net** [comment]
Tracked this down -- the `from_multi_file()` call in numpy-stl 2.10.1 defaults to ASCII mode only, vs autodetection. Filed a ticket at https://code.alephobjects.com/T8415. Apologies for the noise.
